### ISSUE TITLE
how do i paste link ??

### ISSUE THREAD

**Issue by Bhaviisong1thub** [siddharth-tewari/F1-TeamRadio#4]
see i don't know python. so can you help me

**Comment by siddharth-tewari** [comment]
1) Copy the highlighted link and paste it in browser
![image](https://user-images.githubusercontent.com/76590952/175276266-5c80adeb-5880-46d3-b679-62e35bed685f.png)

2) Copy the path 
![image](https://user-images.githubusercontent.com/76590952/175276404-cf73bfc4-64c6-4927-98b7-c8fee7de7ad4.png)

3) Change "TeamRadio.json" with the "path".
![image](https://user-images.githubusercontent.com/76590952/175276667-b41d378b-d3cd-4c6a-aa16-40519a0bd260.png)
-------> 
![image](https://user-images.githubusercontent.com/76590952/175276832-52ab531e-c9b5-4168-9816-7e8ee7e37827.png)

Enter the url and listen.

**Comment by siddharth-tewari** [comment]
I am not so good at python so could not make a feature which automatically does these things.

**Comment by Bhaviisong1thub** [comment]
ok

**Comment by Bhaviisong1thub** [comment]
can i use chrome ??

**Comment by siddharth-tewari** [comment]
Yes
