### ISSUE TITLE
hey, when i paste link it shows "sign in to livetiming.formula1.com"

### ISSUE THREAD

**Issue by Bhaviisong1thub** [siddharth-tewari/F1-TeamRadio#5]
and + it only shows 4 - 5 sec audio clip

**Comment by siddharth-tewari** [comment]
Yes, audio clips are usually short. Would you mind sending a photo just to let me confirm is it as what I guess might be the issue?

**Comment by Bhaviisong1thub** [comment]
![Screenshot (256)](https://user-images.githubusercontent.com/107383936/176164894-3ccfdf13-0180-4276-a372-eb45a7050b19.png)

**Comment by siddharth-tewari** [comment]
> ![Screenshot (256)](https://user-images.githubusercontent.com/107383936/176164894-3ccfdf13-0180-4276-a372-eb45a7050b19.png)

I mean for the "Sign-in" page.

**Comment by Bhaviisong1thub** [comment]
yes

**Comment by siddharth-tewari** [comment]
It wanted you to log-in?

**Comment by Bhaviisong1thub** [comment]
yes

**Comment by siddharth-tewari** [comment]
It asks for log-in only on the main link. It won't for radio links.

**Comment by Bhaviisong1thub** [comment]
ok
