### ISSUE TITLE
How to Install it

### ISSUE THREAD

**Issue by bhoviisonG1THuB** [siddharth-tewari/F1-TeamRadio#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS Information:**
- Additional Information: (If requirement)

**Additional context**

**Comment by siddharth-tewari** [comment]
You can install all the requirements of the code using ```pip install -r requirements.txt```, and then you can run all the codes normally.

**Comment by bhoviisonG1THuB** [comment]
![Capture](https://user-images.githubusercontent.com/124078071/216322406-d44d0b90-4af3-40cb-925e-6f264e816f19.PNG)
Idk what's the problem

**Comment by siddharth-tewari** [comment]
> ![Capture](https://user-images.githubusercontent.com/124078071/216322406-d44d0b90-4af3-40cb-925e-6f264e816f19.PNG) Idk what's the problem

Do you have python installed in your system?

**Comment by bhoviisonG1THuB** [comment]
![Capture](https://user-images.githubusercontent.com/124078071/216803727-30123863-c4c6-4e00-8865-cc8a4e75c60b.PNG)
i can't ope it too

**Comment by bhoviisonG1THuB** [comment]
pls look into this

**Comment by siddharth-tewari** [comment]
Sorry, I cannot help with it. It looks like an error with python instead of the program. You can try manually installing the packages.
